language: node_js
sudo: false
node_js:
  - 5.11.0
env:
  - CXX=g++-4.9
  - PATH=$HOME/purescript:$PATH
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
install:
  - TAG=$(wget -q -O - https://github.com/purescript/purescript/releases/latest --server-response --max-redirect 0 2>&1 | sed -n -e 's/.*Location:.*tag\///p')
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - npm install
  - npm install -g bower
script:
  - npm run build
  - npm test
  - psc-publish --dry-run
